services:
   # 1. Your Self-Contained Go App
  web_app:
    image: image_name_in_ecr
    container_name: swalpaurl_app
    restart: always
    env_file:
      - env_file_name
    expose:
      - "8080"
    depends_on:
      postgres_db:
        condition: service_healthy
      redis_cache:
        condition: service_healthy


  # 2. Your In-Memory Redis Cache Engine
  redis_cache:
    image: redis:7-alpine
    container_name: swalpaurl_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # 3. Your Main PostgreSQL Database Storage
  postgres_db:
    image: postgres:alpine
    container_name: swalpaurl_db
    environment:
      POSTGRES_USER: swalpa_user
      POSTGRES_PASSWORD: swalpa_password
      POSTGRES_DB: swalpaurl
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/migrations/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swalpa_user -d swalpaurl"]
      interval: 5s
      timeout: 5s
      retries: 5


  nginx_proxy:
      image: nginx:alpine
      container_name: swalpaurl_nginx
      ports:
        - "80:80"   
        - "443:443" 
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - /home/ubuntu/swalpaurl_certs:/etc/letsencrypt:ro
      depends_on:
        - web_app




volumes:
  postgres_data:
  webroot_path: