events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s;


    server {
        listen 80;
        server_name swalpa.3utilities.com;


        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name swalpa.3utilities.com;

        ssl_certificate /etc/letsencrypt/live/swalpa.3utilities.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/swalpa.3utilities.com/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            set $backend_service "http://web_app:8080";
            proxy_pass $backend_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
